### ISSUE TITLE
Uncaught ReferenceError: utilMgr is not defined

### ISSUE THREAD

**Issue by obi-wil** [swdotcom/swdc-atom-music-time#34]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Ubuntu 20.04.1
**Thrown From**: [music-time](https://github.com/swdotcom/swdc-atom-music-time) package 2.1.0

### Stack Trace

Uncaught ReferenceError: utilMgr is not defined

```
At /home/wilfredo/.atom/packages/music-time/lib/utils/FileUtil.js:170

ReferenceError: utilMgr is not defined
    at Object.fileUtil.getIntegrations (/packages/music-time/lib/utils/FileUtil.js:170:5)
    at Object.utilMgr.getSlackWorkspaces (/packages/music-time/lib/managers/UtilManager.js:1439:33)
    at Object.utilMgr.updateLoginPreference (/packages/music-time/lib/managers/UtilManager.js:649:21)
    at /packages/music-time/lib/music/SpotifyClient.js:275:21
```

### Commands

```
     -0:11.1.0 Music-Time:refresh-treeview (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-clock 0.1.18 
atom-ide-debugger-node 0.7.3 
atom-ide-debugger-python 0.7.3 
atom-ide-debugger-react-native 0.7.3 
atom-ide-ui 0.13.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-shortcuts 0.0.2 
autocomplete 0.47.0 
code-time 4.4.3 
hey-pane 1.2.0 
Hydrogen 2.14.6 
ide-java 0.9.1 
ide-json 0.2.1 
ide-php 0.7.18 
ide-python 1.7.2 
ide-rust 0.22.0-beta.3 
language-markdown 0.37.0 
markdown-writer 2.11.11 
music-time 2.1.0 
open-recent 5.0.0 
sort-lines 0.19.0 
TabNine 3.0.2 
teletype 0.13.4 
```

**Comment by xavluiz** [comment]
Hi, we apologize for the issue. We're fixing this now and will have an update available shortly.
Thank you.
